# docker-compose file to setup:
# - mysql
# - elasticsearch
# - backend: depends on mysql and elasticsearch
# - frontnend: depends on backend

# This file is meant to aid local development and testing. It *must not* be
# used for production deployment.

version: "3.5"

services:

  mysql8:
    container_name: biotools-mysql8
    image: mysql:8.0.23
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=elixirroot
      - MYSQL_DATABASE=elixir
      - MYSQL_USER=elixir
      - MYSQL_PASSWORD=123
    volumes:
      - "data-mysql8:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - net

  elasticsearch7:
    container_name: biotools-elasticsearch7
    image: elasticsearch:7.12.1
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - "data-elasticsearch7:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - net
      
  backendpy3:
    container_name: biotools-backendpy3
    image: biotools/backendpy3:latest
    build:
      context: ./backend
    environment:
      - BIOTOOLS_ELASTIC_SEARCH_URLS=http://elasticsearch7:9200
      - BIOTOOLS_MYSQL_DB=elixir
      - BIOTOOLS_MYSQL_HOST=mysql8
      - BIOTOOLS_MYSQL_PASSWORD=123
      - BIOTOOLS_MYSQL_USER=elixir
    ports:
      - "8000:80"
    networks:
      - net
    depends_on:
      - mysql8
      - elasticsearch7
    links:
      - mysql8
      - elasticsearch7
    volumes:
      - ./backend:/elixir/application/backend:consistent
      - ./frontend:/elixir/application/frontend

  # dockerfile in frontend dir
  frontendpy3:
    container_name: biotools-frontendpy3
    image: biotools/frontendpy3:latest
    build:
      context: ./frontend
    networks:
      - net
    depends_on:
       - backendpy3
    volumes:
      - ./frontend:/home/biotools/frontend:consistent
      - new-biotools_node_modules:/home/biotools/frontend/node_modules
      - new-biotools_bower_components:/home/biotools/frontend/bower_components


networks:
  net:
    name: biotools-newnet

volumes:
  data-mysql8: {}
  data-elasticsearch7: {}
  new-biotools_node_modules: {}
  new-biotools_bower_components: {}
